### ISSUE TITLE
@StubBeans alike in Spock

### ISSUE THREAD

**Issue by oleksiyp** [Ninja-Squad/springmockk#11]
Check if this idea may add something to this project: https://solidsoft.wordpress.com/2018/09/14/simplify-integration-testing-of-legacy-application-with-spock-1-2/amp/

I trapped it some time ago and put to my backlog. Maybe you can design something similar. Tbh I read it very high level, so fill free to close the ticket.

**Comment by jnizet** [comment]
Unless I misunderstand the article, that use-case is supported out of the box by MockkBean (and the standard MockBean based on Mockito): you can just annotate a test class with `@MockkBean(classes = [SomeBean::class, SomeOtherBean::class])` and a mock will be created for each class and added to the Spring context, replacing the potentially existing bean of that class.

This is not well-known (I didn't know about it until I implemented SpringMockK), but it's [documented here](https://github.com/Ninja-Squad/springmockk/blob/master/src/main/java/com/ninjasquad/springmockk/MockkBean.java#L95-L108), and [tested here](https://github.com/Ninja-Squad/springmockk/blob/master/src/test/kotlin/com/ninjasquad/springmockk/MockBeanOnTestClassForExistingBeanIntegrationTests.kt).

Closing. Feel free to ask for reopening if I misundersstood something.
