### ISSUE TITLE
Compability with KotlinTest?

### ISSUE THREAD

**Issue by fipp** [Ninja-Squad/springmockk#26]
Hi! After going through the https://spring.io/guides/tutorials/spring-boot-kotlin/ tutorial that makes use of JUnit5 and SpringMockK, I thought I'd try to reimplement the same tests with KotlinTest and SpringMockK.

When interacting on the mock (a jpa repository) in the test, I get the error: `kotlin.UninitializedPropertyAccessException: lateinit property userRepository has not been initialized`

The mock is set up the same way as in the JUnit5 test, where it works fine:

```kotlin
@MockkBean
private lateinit var userRepository: UserRepository
```

Any pointers on making SpringMockK work with KotlinTest instead of JUnit5?

Cheers!

**Comment by jnizet** [comment]
MockkBean can only do its job if it's used inside a Spring integration test, i.e. a test where the JUnit 5 SpringExtension is used, or where the JUnit4 SpringRunner is used.

I know nothing about KotlinTest, and thus don't know if there is an equivalent Spring extension/runner for KotlinTest. AFAIK, Spring itself doesn't provide any support for KotlinTest.
