### ISSUE TITLE
Readme suggests usage of version 2.2.0 but latest release is 2.0.0

### ISSUE THREAD

**Issue by ideskov** [Ninja-Squad/springmockk#34]
Hey,

Usage section in readme suggests that we should use version 2.2.0 `testImplementation("com.ninja-squad:springmockk:2.2.0")` but the latest release is 2.0.0. It's a bit confusing, could we possibly fix that :)

Thanks

**Comment by jnizet** [comment]
Oops. Good catch! Thanks for the report.
