### ISSUE TITLE
Allow MockkBean and SpykBean use private methods

### ISSUE THREAD

**Issue by prestuhome** [Ninja-Squad/springmockk#35]
Using mockk, I can specify `recordPrivateCalls`:
```
val service = spyk<SomeService>(recordPrivateCalls = true)
```
Can you add same functionality for MockkBean and SpykBean;
```
@SpykBean(recordPrivateCalls = true)
@Autowired
lateinit var service: SomeService
```

**Comment by jnizet** [comment]
On SpykBean, I guess i could. On MockkBean, it wouldn't make sense.

But could you please explain why you need this, with an example use-case? I very rarely use spies, and even less with `recordPrivateCalls` set to true, and I wonder when it might be useful, needed or a good idea to do this.

**Comment by prestuhome** [comment]
I want to test CachingService and @Cacheable method of some service.
Service:
```
@Service
class Service : AbstractService(key = "SOME_KEY") {
    @Cacheable(
            value = ["cache"],
            key = "#root.target.key",
            unless = "#result == null"
    )
    fun doSmth() {
        return true
    }
}
```
Test:
```
class CachingTest {

    @SpykBean
    @Autowired
    lateinit var service: Service

    @Test
    fun cachingTest() {
        executeCaching()
        verify(exactly = 1) { service.doSmth() }
        verify(exactly = 1) { cachingService.cleanAllCache() } // because it is invoked before test

        cachingService.cleanAllCache()

        executePartnerCaching()
        verify(exactly = 2) { service.doSmth() }
        verify(exactly = 2) { cachingService.cleanAllCache() }
    }

    private fun executeCaching() {
        for (i in 1..5) {
            assertThat(service.doSmth()).isEqualTo(true)
        }
    }
}
```

So i have exception like this:
```
java.lang.AssertionError: Verification failed: call 1 of 5: Service(Service#1).getKey()). 23 matching calls found, but needs at least 5 and at most 5 calls
```
That happened because of verify parameter `verifyBlock: io.mockk.MockKVerificationScope.() -> kotlin.Unit` is lambda and takes first call. In my case it is key of cachable method `key = "#root.target.key"`
So i changed the service like this;
```
@Service
class Service : AbstractService(key = "SOME_KEY") {
    @Cacheable(
            value = ["cache"],
            key = "#root.target.key",
            unless = "#result == null"
    )
    fun doSmth() {
        return _doSmth()
    }

    private fun _doSmth() {
        return true
    }
}
```
And i want to use private calls in my test:
Test:
```
class CachingTest {

    @SpykBean(recordPrivateCalls = true)
    @Autowired
    lateinit var service: Service

    @Test
    fun cachingTest() {
        executeCaching()
        verify(exactly = 1) { service["_doSmth"]() }
        verify(exactly = 1) { cachingService.cleanAllCache() } // because it is invoked before test

        cachingService.cleanAllCache()

        executePartnerCaching()
        verify(exactly = 2) { service["_doSmth"]() }
        verify(exactly = 2) { cachingService.cleanAllCache() }
    }

    private fun executeCaching() {
        for (i in 1..5) {
            assertThat(service.doSmth()).isEqualTo(true)
        }
    }
}
```

I hope you understand the case

**Comment by jnizet** [comment]
TBH, I'm not sure I completely understand. But before going further, could you please check that recording private calls would solve your issue? You can do that by configuring MockK to always record private calls, by following the instructions here: https://mockk.io/#settings-file

**Comment by pihentagy** [comment]
I second on this request.

I don't need global recordPrivateCalls, but I don't want to make a method public just to be able to verify it was called.

I have this line not to bother with constructor arguments

```kotlin
@SpykBean private lateinit var myApp: MyApp
```

but I don't know how to record private calls after that.
