### ISSUE TITLE
What prevents it from being part of spring?

### ISSUE THREAD

**Issue by mikhail-putilov** [Ninja-Squad/springmockk#36]
Hi, that's an awesome library. Many thanks for it!
I'd like to use it on my daily work basis but I cannot bring something on the table that's not supported officially by spring.

Did you try to donate the project to spring? Did they say anything?

**Comment by cexbrayat** [comment]
👋 Hi @mikhail-putilov 
Thank you for the praise! @jnizet deserves it as the author and main maintainer, I'm just answering while he is on vacation.

Your question makes sense, it has been discussed and the Spring team declined at the time. See https://github.com/mockk/mockk/issues/140 for full context. Maybe that'll change in the future but I think everyone is happy with the current situation for now. We are actively maintaining and using the library, and a growing number of developers do as well. 

I would honestly not worry too much about bringing it in your projects, as it is a fairly low maintenance project now, and we mainly just follow the releases (see https://github.com/Ninja-Squad/springmockk/commits/master). No real risks there.
But I completely understand that it may not suit your needs, that's the beauty and curse of open-source 🙂

**Comment by emersonf** [comment]
I'm hoping they reconsider.

https://github.com/spring-projects/spring-boot/issues/15749#issuecomment-684669770
