### ISSUE TITLE
Maven artifact is missing .module files

### ISSUE THREAD

**Issue by checketts** [Ninja-Squad/springmockk#56]
A while ago (around Gradle 5.3) Gradle introduced an additional piece of metadata to present more dependency details beyond what Maven has historically offered (see https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html)

This means that a `.module` will also be published to the repository. Gradle also adds a comment to the `pom.xml` to indicate that the richer metadata is available: (see https://repo1.maven.org/maven2/com/ninja-squad/springmockk/3.0.0/springmockk-3.0.0.pom)

```
 <!--
 This module was also published with a richer model, Gradle metadata,  
-->
<!--
 which should be used instead. Do not delete the following line which  
-->
<!--
 is to indicate to Gradle or any Gradle module metadata file consumer  
-->
<!-- that they should prefer consuming it instead. -->
<!-- do_not_remove: published-with-gradle-metadata -->
```

Springmockk is not publishing the `.module` files (See listing https://repo1.maven.org/maven2/com/ninja-squad/springmockk/3.0.0/)

For comparison you can see the kotling-logging Maven artifacts include the `.module` file: https://repo1.maven.org/maven2/io/github/microutils/kotlin-logging/2.0.4/

There are 2 potential solutions:

## Option 1- [Disable metadata](https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html#sub:disabling-gmm-publication ): 

This will remove the comment from the pom.xml and so Gradle won't continue to check for the `.module` file.

```
    tasks.withType<GenerateModuleMetadata> {
        enabled = false
    }
```

## Option 2- Update the maven publishing to include the missing files

This is the better long-term solution. However I don't have a direct recommendation since I don't have experience in that regard and don't know what is mis-configured.

## Why hasn't this been a problem before?

When using `mavenCentral()` as a repo directly, it serves up a 404 for the missing `.module` file and Gradle recovers fine. However when using an internal repository like Artifactory, it is common to configure it to return `403` for missing files to try to obscure data that shouldn't be accessible.

So to reproduce this you would need to use Gradle > 5.3, Using Springmockk as a dependency, when using a locked dow Maven repository that is configured to serve 403 instead of exposing 404 for missing artifacts.

**Comment by jnizet** [comment]
Thanks @checketts for this very detailed issue. 

I use the gradle bintray plugin to publish, and unfortunately, it's not well maintained and doesn't publish the module metadata. A workaround for the issue, until I fix it, you can clone the project, make sure you use Java 8, and run `./gradlew publishMavenPublicationToMavenLocal`. This will generate the module file under `~/.m2/repository/com/ninja-squad/springmockk/3.0.0/springmockk-3.0.0.module`, that you can probably store in your internal repository.

It would be nice, BTW, if you could tell me if that works fine, and if everything is fine with your project when using the module metadata.

It's apparently not a big deal to sign and publish to bintray, and then sync with Maven central, with the native maven-publish plugin, which publishes the module metadata, so I will try doing that and will keep you in touch when is done.

**Comment by checketts** [comment]
The maven local install worked. I'll work with my build team tomorrow to see if I can convince them to do the manual install of the files I've generated.

Thanks for the quick response and looking into a long-term fix.

**Comment by jnizet** [comment]
Hi @checketts I changed my publishing process so that the gradle module metadata are published. The version 3.0.1 has been released in jcenter, and should be available in Maven Central soon (it always takes a few hours).

**Comment by jnizet** [comment]
Version 3.0.1 is now available in Maven Central, with the module file.
