### ISSUE TITLE
Is there any workaround to use @MockkBean on a Kotlin interface property?

### ISSUE THREAD

**Issue by sillyquestion** [Ninja-Squad/springmockk#76]
Is there any workaround to use @MockkBean on a Kotlin interface property?
At present when I try it I get an error message 'This annotation is not applicable to target 'member property without backing field or delegate''

**Comment by jnizet** [comment]
Hy @ sillyquestion. I'm not sure what your goal is. The MockkBean annotation is used to annotate a property of a JUnit test class. JUnit tests can't be interfaces.
