### ISSUE TITLE
Test failures after spring boot update to 2.6.1

### ISSUE THREAD

**Issue by vikhyatprabhu** [Ninja-Squad/springmockk#83]
Recently doing a migration from 2.2.5 Spring boot version to 2.6.1 in our Kotlin Spring boot project and we are finding that , some integration tests are failing . I have updated the springmockk version to 3.1.1 which is the latest but still we are getting the following exception when 
calling the controller 

org.springframework.http.converter.HttpMessageNotReadableException

Considering that this worked with older version of spring boot , I suspect there is a compatibility issue . I see there are some updated changes which do the spring boot update of a library , would it be possible to release those changes ?

**Comment by jnizet** [comment]
Hi @vikhyatprabhu 

If you want me to investigate, you'll have to provide a minimal but complete example, as an public git repo or as a zip file, that reproduces the issue. Frankly, I doubt this exception you're getting has anything to do with SpringMockK: it's not involved at all in deciding whether an HTTP message is readable or not.

**Comment by vikhyatprabhu** [comment]
We can close this issue as I found the issue was not related to springmockk library but related to json deserializing on our end . Thank you for your quick response and sorry for the confusion
