### ISSUE TITLE
Partial Mocking with @SpykBean Does Not Work for Composite Beans

### ISSUE THREAD

**Issue by rsteppac** [Ninja-Squad/springmockk#92]
**Versions**

springmockk version: 3.1.1
mockk version: 1.13.2
SpringBoot version: 2.7.5

**Scenario**

Consider the following composite bean for the application configuration:
```kotlin
@ConstructorBinding
@ConfigurationProperties("abc")
data class AppConfig(
    val greeting: String,
    val upstreamService: HttpService
) {

    data class HttpService(
        val hostname: String,
        val port: Int,
    )
}
```
and the following SpringBoot test:
```kotlin
@SpringBootTest(properties = [
        "abc.greeting=I come in peace",
        "abc.upstream-service.hostname=localhost",
        "abc.upstream-service.port=0",
    ]
)
@ExtendWith(MockKExtension::class)
class MyApplicationTests {

    @SpykBean
    private lateinit var appConfig: AppConfig
    
    private lateinit var mockServer: MockWebServer

    @BeforeEach
    fun setUp() {
        mockServer = MockWebServer()
        mockServer.start()
        
        every{appConfig.upstreamService.port} returns mockServer.port
    }

    @AfterEach
    fun tearDown() {
        mockServer.shutdown()
    }

    @Test
    fun testSpyk() {
        assertEquals(mockServer.port, appConfig.upstreamService.port)
        assertEquals("localhost", appConfig.upstreamService.hostname)
    }
}
```

**Expected Behavior**

The test should pass. `appConfig.upstreamService.port` is stubbed and should return the mock server's port while `appConfig.upstreamService.hostname` should return the value configured in the application context.

**Actual Behavior**

The test fails on the call `appConfig.upstreamService.hostname` because no answer can be found. I.e. the `HttpService` bean has been mocked instead of being wrapped in a spy to allow for partial mocking.

**Comment by jnizet** [comment]
To be honest, I'm even surprised you can call `every{ appConfig.upstreamService.port } returns mockServer.port`: I would have expected `appConfig` to be a spy, but not `appConfig.upstreamService`.

But anyway, this is not related to SpringMockK per se, but to MockK in general, since the following test, where SpringMockK is not involved, fails for the exact same reason as your test:

```
    @Test
    fun testNestedSpy() {
        val appConfig = AppConfig(
            greeting = "hello",
            upstreamService = AppConfig.HttpService(
                port = 0,
                hostname = "localhost"
            )
        )

        val spiedAppConfig = spyk(appConfig) {
            every { upstreamService.port } returns 8080
        }

        assertEquals(8080, spiedAppConfig.upstreamService.port)
        assertEquals("localhost", spiedAppConfig.upstreamService.hostname)
    }
```

So you should post this issue on the MockK project.
